assets:
  npmrc: zerocracy/home#assets/npmrc
install: |
  sudo apt-get -y update
  sudo gem install pdd
  sudo npm install --no-color --global gulp
  npm install --no-color
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    gulp
    npm version "${tag}"
    git add -f dist/colorize-${tag}.min.js
    git commit -am "Added JS file for ${tag}"
    mv dist/colorize-${tag}.min.js /tmp
    branch=$(git rev-parse --abbrev-ref HEAD)
    git checkout gh-pages
    git reset --hard
    mv /tmp/colorize-${tag}.min.js .
    cp colorize-${tag}.min.js colorize.min.js
    git add colorize-${tag}.min.js
    git add colorize.min.js
    git commit --allow-empty -am "${tag}"
    git checkout "${branch}"
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
architect:
- yegor256
merge:
  script: |-
    gulp
    pdd -f /dev/null -v
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
